### ISSUE TITLE
Mouse not working when using keyboard on wine with box64 and hangover 

### ISSUE THREAD

**Issue by m1m1k4tz** [slp/krun#14]

**Comment by m1m1k4tz** [comment]
The mouse seems pretty slow but the app should be running fast on low settings

**Comment by teohhanhui** [comment]
Does the VM have enough RAM? Are you using this branch?

https://github.com/teohhanhui/krun/tree/feat/balloon-more-ram

**Comment by m1m1k4tz** [comment]
I just tried that branch but the mouse is still laggy even just in the menu paused the game is fine though

**Comment by m1m1k4tz** [comment]
This turned out to be a missing gstreamer plugin

**Comment by teohhanhui** [comment]
@m1m1k4tz Do you think I should add rpmfusion multimedia setup to my guide? 🙈

**Comment by m1m1k4tz** [comment]
This actually is an issue where my mouse won’t work in game when using my keyboard

**Comment by m1m1k4tz** [comment]
That’s all I need and fallout 3 would be playable I opened a bug report for steam on the wow64 mode so that should work soon too

**Comment by m1m1k4tz** [comment]
I just tried in half life 1 and it happens there too

**Comment by m1m1k4tz** [comment]
What do you think is this box64 or krun? Maybe a package is needed in distrobox?

**Comment by m1m1k4tz** [comment]
Apparently this is an Apple keyboard problem because on every app that happens if you plugin a different keyboard it fixes the problem

**Comment by m1m1k4tz** [comment]
@asahilina

**Comment by m1m1k4tz** [comment]
Actually this was a KDE option I wasn’t used to
