### ISSUE TITLE
Cannot build with nix, libkrun.h not found

### ISSUE THREAD

**Issue by RossComputerGuy** [slp/krun#15]
`libkrun.h` is not found, `krun` has this problem but not `krunvm`.

```
error: failed to run custom build command for `krun-sys v1.8.1 (/build/source/crates/krun-sys)`

Caused by:
  process didn't exit successfully: `/build/source/target/release/build/krun-sys-c928935194fd9ad3/build-script-build` (exit status: 101)
  --- stdout
  cargo::rerun-if-changed=wrapper.h
  cargo::rustc-link-lib=krun

  --- stderr
  wrapper.h:1:10: fatal error: 'libkrun.h' file not found
  thread 'main' panicked at crates/krun-sys/build.rs:11:10:
  Unable to generate bindings: ClangDiagnostic("wrapper.h:1:10: fatal error: 'libkrun.h' file not found\n")
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Derivation:
```nix
pkgs.rustPlatform.buildRustPackage rec {
  pname = "krun";
  version = "git+${src.rev}";

  src = pkgs.fetchFromGitHub {
    owner = "slp";
    repo = "krun";
    rev = "5a8542a5066bd1a4d8bad99236f05ea3ac687ef7";
    hash = "sha256-3w1JHqzpkF11+3yHN3yPu2dKdi4qXdO8HY+7ICugAZA=";
  };

  cargoHash = "sha256-dtj3TiszBBsMtlJaaIyTmCNAGZy/zuSGSK8OOTb5Xmg=";

  buildInputs = [
    libkrun
  ];

  cargoLock.lockFile = "${src}/Cargo.lock";
  env.LIBCLANG_PATH = "${pkgs.llvmPackages_latest.clang-unwrapped.lib}/lib/libclang.so";
}
```

**Comment by teohhanhui** [comment]
Please make sure `libkrun.h` is somewhere in your `LD_LIBRARY_PATH`. This seems like a nix configuration problem to me.

**Comment by RossComputerGuy** [comment]
> Please make sure `libkrun.h` is in a directory somewhere in your `LD_LIBRARY_PATH`.

Why `LD_LIBRARY_PATH`? That is for shared/static libraries and not headers.

> This seems like a nix configuration problem to me.

I thought this was more of a krun issue, it should be able to find `libkrun.h` since Nix uses a wrapper CC and one of the envs set is `NIX_CFLAGS_COMPILE=" -frandom-seed=szx61zmmcn -isystem /nix/store/qk0xhr68pxpdchr6xwf14xxjf7m1ak92-libkrun-git+0bea04816f4dc414a947aa7675e169cbbfbd45dc/include"`. This adds the libkrun package's include directory to the search path for CC.

**Comment by RossComputerGuy** [comment]
> Please make sure `libkrun.h` is in a directory somewhere in your `LD_LIBRARY_PATH`.

This does not help. I exported it as `LD_LIBRARY_PATH="/nix/store/qk0xhr68pxpdchr6xwf14xxjf7m1ak92-libkrun-git+0bea04816f4dc414a947aa7675e169cbbfbd45dc/lib:/nix/store/qk0xhr68pxpdchr6xwf14xxjf7m1ak92-libkrun-git+0bea04816f4dc414a947aa7675e169cbbfbd45dc"` and still build failure.

**Comment by teohhanhui** [comment]
> Why `LD_LIBRARY_PATH`? That is for shared/static libraries and not headers.

My bad! I was replying on the go and wasn't thinking lol

Can you check if `libkrun.h` is indeed in your include path? (i.e. `-I` flag to the linker)

**Comment by RossComputerGuy** [comment]
> Can you check if `libkrun.h` is indeed in your include path? (i.e. `-I` flag to the linker)

It wasn't in `NIX_LDFLAGS` so I added it and now it fails earlier:
```
   Compiling glob v0.3.1
   Compiling proc-macro2 v1.0.82
   Compiling unicode-ident v1.0.12
   Compiling libc v0.2.154
   Compiling minimal-lexical v0.2.1
   Compiling regex-syntax v0.8.3
   Compiling memchr v2.7.2
   Compiling cfg_aliases v0.1.1
   Compiling utf8parse v0.2.1
   Compiling bindgen v0.69.4
   Compiling rustix v0.38.34
   Compiling either v1.11.0
   Compiling bitflags v2.5.0
   Compiling itertools v0.12.1
   Compiling nix v0.28.0
   Compiling clang-sys v1.7.0
error: failed to run custom build command for `proc-macro2 v1.0.82`

Caused by:
  could not execute process `/build/source/target/release/build/proc-macro2-9bf00e321e6622a6/build-script-build` (never executed)

Caused by:
  Permission denied (os error 13)
warning: build failed, waiting for other jobs to finish...
```

First time seeing this error.

**Comment by teohhanhui** [comment]
You need to use `bindgenHook`: https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/rust.section.md#hooks-hooks

**Comment by RossComputerGuy** [comment]
That worked
