### ISSUE TITLE
krun ls fails due to operation not supported

### ISSUE THREAD

**Issue by RossComputerGuy** [slp/krun#18]
```
$ RUST_LOG=debug krun ls /
[2024-05-30T01:48:38Z DEBUG krun::net] passing fd to passt fd=5
Error: Failed to configure net mode

Caused by:
    Operation not supported (os error 95)
No IPv4 nameserver available for DHCP
No IPv6 nameserver available for NDP/DHCPv6
```

**Comment by slp** [comment]
Looks like `libkrun` was build without `net` support. For using `krun`, you need to build it with `--features blk,net,gpu`.

**Comment by RossComputerGuy** [comment]
> Looks like `libkrun` was build without `net` support.

Enabled and the operation not supported error is gone.


> For using `krun`, you need to build it with `--features blk,net,gpu`.

Tried enabling those but got an error saying no packages provided it.

I still get the "no nameserver" messages though.

**Comment by RossComputerGuy** [comment]
> Sounds like `passt` has some problem with your DNS config. Is there something special about it?

Not really, I use Tailscale plus I run resolved to send my DNS traffic to my NAS.

**Comment by teohhanhui** [comment]
@RossComputerGuy For the DNS resolver issue, see #17 for some similar cases. Let's continue the diagnosis there.

**Comment by RossComputerGuy** [comment]
Alright, and #19 is relevant as well after setting `RUST_LOG=debug` and seeing the same behavior (excluding the networking stuff).
