### ISSUE TITLE
Application window not visible

### ISSUE THREAD

**Issue by Enellis** [slp/krun#3]
When launching a GUI application, the window fails to appear on the screen, though it does show up in the application bar. However, the application executes as expected, and the desired output is visible in the command line output:

[Screencast_20240511_104554.webm](https://github.com/slp/krun/assets/6263698/f0d84ef0-61cc-4bf9-bd25-a5fa51f5b9cc)

The issue persists regardless of what application and whether the application is launched directly or through FEXBash.

Interestingly, this problem is not present when compiling and running the legacy C version of krun.

**Comment by SO5005** [comment]
#4 This should fix it.

**Comment by Enellis** [comment]
Yes, it works with this PR. Thank you very much.

**Comment by slp** [comment]
Fixed by #4, closing it.
