### ISSUE TITLE
dhclient is EOL

### ISSUE THREAD

**Issue by RossComputerGuy** [slp/krun#36]
Related page: https://www.isc.org/blogs/isc-dhcp-eol/

Code: https://github.com/slp/krun/blob/3c6f9419aa170617be07d109151b53c54f45ff4e/crates/krun-guest/src/net.rs#L21

`krun` shouldn't rely on an EOL package, trying to package this for NixOS reveals we need to package dhclient ourselves which is not idea. Instead an alternative supported and still maintained package should be used instead.

**Comment by teohhanhui** [comment]
Actually, `dhclient` has been EOL since end of 2021: https://lists.isc.org/pipermail/dhcp-users/2021-June/022495.html

**Comment by teohhanhui** [comment]
https://fedoraproject.org/wiki/Changes/dhclient_deprecation#Detailed_Description
